import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import client from "../lib/client";

const Home: NextPage = () => {
  const [res, setRes] = useState("res");

  const click = async () => {
    const { hello } = await client.test();
    setRes(hello);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Test page</h1>
        <button onClick={click}>Fetch</button>
        <pre>{res}</pre>
      </main>
    </div>
  );
};

export default Home;
